### ISSUE TITLE
Default MPH Skin displays in km

### ISSUE THREAD

**Issue by kevindwood** [Funbit/ets2-telemetry-server#47]
When loading Default MPH Skin the odometer reads in kilometers and not in miles as it does in the truck

**Comment by Funbit** [comment]
Thank you for the report. Fixed in the latest version.

**Comment by kevindwood** [comment]
I just downloaded the latest version approximately 60 minutes ago, and it is not fixed.  Both the "Default MPH/KMh" odometer shows as kilometers

**Comment by Funbit** [comment]
Please try to download again, it was changed after commit.
